import { Lead, Conversation, AIMemory, Appointment, FollowUp, BusinessKnowledge } from "@/types";

// ============================================
// Mock Data for Development & Demo
// ============================================

export const mockLeads: Lead[] = [
  {
    id: "LD-001",
    conversationId: "",
    fullName: "Sarah Mitchell",
    email: "sarah.mitchell@techcorp.com",
    phone: "+1 (555) 234-5678",
    source: "Website",
    businessType: "SaaS",
    leadScore: 92,
    intent: "high",
    urgency: "urgent",
    status: "qualified",
    bookedCall: true,
    reminderSent: true,
    createdDate: "2025-01-15T09:30:00Z",
    lastContactTime: "2025-01-28T14:22:00Z",
  },
  {
    id: "LD-002",
    conversationId: "",
    fullName: "James Rodriguez",
    email: "j.rodriguez@innovate.io",
    phone: "+1 (555) 345-6789",
    source: "LinkedIn",
    businessType: "E-commerce",
    leadScore: 78,
    intent: "high",
    urgency: "high",
    status: "contacted",
    bookedCall: true,
    reminderSent: false,
    createdDate: "2025-01-18T11:15:00Z",
    lastContactTime: "2025-01-27T10:45:00Z",
  },
  {
    id: "LD-003",
    conversationId: "",
    fullName: "Emily Chen",
    email: "emily.chen@startup.co",
    phone: "+1 (555) 456-7890",
    source: "Referral",
    businessType: "FinTech",
    leadScore: 85,
    intent: "high",
    urgency: "medium",
    status: "qualified",
    bookedCall: false,
    reminderSent: true,
    createdDate: "2025-01-20T08:00:00Z",
    lastContactTime: "2025-01-26T16:30:00Z",
  },
  {
    id: "LD-004",
    conversationId: "",
    fullName: "Michael Foster",
    email: "m.foster@enterprise.com",
    phone: "+1 (555) 567-8901",
    source: "Google Ads",
    businessType: "Healthcare",
    leadScore: 64,
    intent: "medium",
    urgency: "medium",
    status: "new",
    bookedCall: false,
    reminderSent: false,
    createdDate: "2025-01-22T13:45:00Z",
    lastContactTime: "2025-01-25T09:15:00Z",
  },
  {
    id: "LD-005",
    conversationId: "",
    fullName: "Olivia Brown",
    email: "olivia.b@design.studio",
    phone: "+1 (555) 678-9012",
    source: "Instagram",
    businessType: "Agency",
    leadScore: 71,
    intent: "medium",
    urgency: "low",
    status: "contacted",
    bookedCall: false,
    reminderSent: true,
    createdDate: "2025-01-23T10:30:00Z",
    lastContactTime: "2025-01-24T11:20:00Z",
  },
  {
    id: "LD-006",
    conversationId: "",
    fullName: "David Kim",
    email: "david.kim@techventures.io",
    phone: "+1 (555) 789-0123",
    source: "Website",
    businessType: "AI/ML",
    leadScore: 95,
    intent: "high",
    urgency: "urgent",
    status: "converted",
    bookedCall: true,
    reminderSent: true,
    createdDate: "2025-01-10T07:00:00Z",
    lastContactTime: "2025-01-28T16:00:00Z",
  },
  {
    id: "LD-007",
    conversationId: "",
    fullName: "Amanda Torres",
    email: "a.torres@consulting.com",
    phone: "+1 (555) 890-1234",
    source: "Facebook",
    businessType: "Consulting",
    leadScore: 45,
    intent: "low",
    urgency: "low",
    status: "new",
    bookedCall: false,
    reminderSent: false,
    createdDate: "2025-01-25T15:20:00Z",
    lastContactTime: "2025-01-25T15:20:00Z",
  },
  {
    id: "LD-008",
    conversationId: "",
    fullName: "Robert Zhang",
    email: "r.zhang@manufacturing.co",
    phone: "+1 (555) 901-2345",
    source: "Referral",
    businessType: "Manufacturing",
    leadScore: 58,
    intent: "medium",
    urgency: "medium",
    status: "contacted",
    bookedCall: false,
    reminderSent: true,
    createdDate: "2025-01-19T12:00:00Z",
    lastContactTime: "2025-01-27T08:30:00Z",
  },
  {
    id: "LD-009",
    conversationId: "",
    fullName: "Jessica Park",
    email: "j.park@realestate.com",
    phone: "+1 (555) 012-3456",
    source: "Google Ads",
    businessType: "Real Estate",
    leadScore: 82,
    intent: "high",
    urgency: "high",
    status: "qualified",
    bookedCall: true,
    reminderSent: true,
    createdDate: "2025-01-14T09:45:00Z",
    lastContactTime: "2025-01-28T12:15:00Z",
  },
  {
    id: "LD-010",
    conversationId: "",
    fullName: "Chris Anderson",
    email: "c.anderson@retail.shop",
    phone: "+1 (555) 123-4567",
    source: "Website",
    businessType: "Retail",
    leadScore: 33,
    intent: "low",
    urgency: "low",
    status: "lost",
    bookedCall: false,
    reminderSent: true,
    createdDate: "2025-01-08T14:30:00Z",
    lastContactTime: "2025-01-20T10:00:00Z",
  },
  {
    id: "LD-011",
    conversationId: "",
    fullName: "Nina Patel",
    email: "nina.p@edtech.io",
    phone: "+1 (555) 234-5679",
    source: "LinkedIn",
    businessType: "EdTech",
    leadScore: 88,
    intent: "high",
    urgency: "high",
    status: "qualified",
    bookedCall: true,
    reminderSent: false,
    createdDate: "2025-01-16T08:15:00Z",
    lastContactTime: "2025-01-28T09:00:00Z",
  },
  {
    id: "LD-012",
    conversationId: "",
    fullName: "Tom Wilson",
    email: "tom.w@logistics.co",
    phone: "+1 (555) 345-6780",
    source: "Referral",
    businessType: "Logistics",
    leadScore: 73,
    intent: "medium",
    urgency: "medium",
    status: "contacted",
    bookedCall: false,
    reminderSent: true,
    createdDate: "2025-01-21T11:30:00Z",
    lastContactTime: "2025-01-26T14:45:00Z",
  },
];

export const mockConversations: any[] = [
  {
    id: "CV-001",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    userMessage: "Hi, I'm interested in your AI automation services. Can you tell me more about pricing?",
    aiResponse: "Hello Sarah! Thank you for your interest. Our AI automation packages start at $499/month for small businesses and scale based on your needs. Would you like to schedule a call to discuss which plan would be the best fit for your SaaS company?",
    timestamp: "2025-01-15T09:32:00Z",
    channel: "web",
    messageType: "inbound",
  },
  {
    id: "CV-002",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    userMessage: "Yes, I'd love to schedule a call. What times are available this week?",
    aiResponse: "I have several slots available this week. How about Tuesday at 2 PM EST or Wednesday at 10 AM EST? I can also check other times if those don't work for you.",
    timestamp: "2025-01-15T09:35:00Z",
    channel: "web",
    messageType: "inbound",
  },
  {
    id: "CV-003",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    userMessage: "Wednesday at 10 AM works perfectly!",
    aiResponse: "Excellent! I've booked your appointment for Wednesday, January 22nd at 10 AM EST. You'll receive a calendar invite shortly with a Zoom link. Is there anything specific you'd like us to prepare for the call?",
    timestamp: "2025-01-15T09:38:00Z",
    channel: "web",
    messageType: "inbound",
  },
  {
    id: "CV-004",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    userMessage: "We're looking for an AI solution to handle our customer support chatbot. Our current system is overwhelmed.",
    aiResponse: "Hi James! I understand the challenge. Our AI-powered customer support solution can handle up to 80% of common queries automatically, significantly reducing your team's workload. For e-commerce businesses like yours, we've seen resolution times drop by 60%. Would you like to see a demo?",
    timestamp: "2025-01-18T11:18:00Z",
    channel: "email",
    messageType: "inbound",
  },
  {
    id: "CV-005",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    userMessage: "That sounds great! Can we do a demo this week?",
    aiResponse: "Absolutely! I can set up a personalized demo for Thursday at 3 PM EST. During the demo, I'll show you how our AI handles product inquiries, order tracking, and returns — all common queries for e-commerce. Sound good?",
    timestamp: "2025-01-18T11:22:00Z",
    channel: "email",
    messageType: "inbound",
  },
  {
    id: "CV-006",
    leadId: "LD-003",
    leadName: "Emily Chen",
    userMessage: "I was referred by David Kim. He mentioned you helped his company with AI lead qualification.",
    aiResponse: "Welcome Emily! David is one of our valued clients. Yes, we helped TechVentures implement our AI lead qualification system, which increased their qualified lead rate by 40%. Since you're in FinTech, we have specialized solutions for financial services. Would you like to learn more about our compliance-ready AI solutions?",
    timestamp: "2025-01-20T08:05:00Z",
    channel: "web",
    messageType: "inbound",
  },
  {
    id: "CV-007",
    leadId: "LD-006",
    leadName: "David Kim",
    userMessage: "The AI system has been amazing. We want to expand to our other product lines.",
    aiResponse: "That's wonderful to hear, David! I'm glad the system is performing well. For expanding to additional product lines, we can replicate the current setup with customized training data for each line. I'll prepare a scaling proposal for you. Would next Monday work for a strategy session?",
    timestamp: "2025-01-28T16:00:00Z",
    channel: "web",
    messageType: "inbound",
  },
  {
    id: "CV-008",
    leadId: "LD-009",
    leadName: "Jessica Park",
    userMessage: "I need an AI assistant that can handle property inquiries and schedule viewings automatically.",
    aiResponse: "Hi Jessica! Our real estate AI solution is perfect for that. It can answer property questions, check availability, and schedule viewings 24/7. Our real estate clients see a 3x increase in viewing bookings. I'd love to show you a demo tailored to your listings. When works best?",
    timestamp: "2025-01-14T09:50:00Z",
    channel: "phone",
    messageType: "inbound",
  },
];

export const mockMemories: AIMemory[] = [
  {
    id: "MEM-001",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    memoryType: "preference",
    memoryValue: "Prefers morning meetings. Uses Zoom for video calls.",
    lastUpdated: "2025-01-15T09:38:00Z",
  },
  {
    id: "MEM-002",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    memoryType: "intent",
    memoryValue: "Looking for AI automation to streamline customer onboarding for SaaS platform.",
    lastUpdated: "2025-01-15T09:35:00Z",
  },
  {
    id: "MEM-003",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    memoryType: "context",
    memoryValue: "Current support system overwhelmed. Team of 5 support agents. E-commerce platform on Shopify.",
    lastUpdated: "2025-01-18T11:22:00Z",
  },
  {
    id: "MEM-004",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    memoryType: "objection",
    memoryValue: "Concerned about AI accuracy with technical product questions. Wants human fallback option.",
    lastUpdated: "2025-01-19T14:00:00Z",
  },
  {
    id: "MEM-005",
    leadId: "LD-003",
    leadName: "Emily Chen",
    memoryType: "context",
    memoryValue: "Referred by David Kim (LD-006). FinTech company needs compliance-ready AI solutions.",
    lastUpdated: "2025-01-20T08:05:00Z",
  },
  {
    id: "MEM-006",
    leadId: "LD-006",
    leadName: "David Kim",
    memoryType: "behavior",
    memoryValue: "Highly engaged. Quick to respond. Decision-maker. Already using product successfully.",
    lastUpdated: "2025-01-28T16:00:00Z",
  },
  {
    id: "MEM-007",
    leadId: "LD-006",
    leadName: "David Kim",
    memoryType: "timeline",
    memoryValue: "Wants to expand AI to 3 additional product lines by Q2 2025.",
    lastUpdated: "2025-01-28T16:05:00Z",
  },
  {
    id: "MEM-008",
    leadId: "LD-009",
    leadName: "Jessica Park",
    memoryType: "preference",
    memoryValue: "Prefers phone calls over email. Afternoon availability. 50+ active listings.",
    lastUpdated: "2025-01-14T10:00:00Z",
  },
  {
    id: "MEM-009",
    leadId: "LD-009",
    leadName: "Jessica Park",
    memoryType: "intent",
    memoryValue: "Needs 24/7 property inquiry handling and automated viewing scheduling.",
    lastUpdated: "2025-01-14T09:55:00Z",
  },
  {
    id: "MEM-010",
    leadId: "LD-011",
    leadName: "Nina Patel",
    memoryType: "context",
    memoryValue: "EdTech startup. 10K+ students. Needs AI tutoring assistant and student engagement tracking.",
    lastUpdated: "2025-01-16T08:20:00Z",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "APT-001",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    appointmentDate: "2025-01-22",
    appointmentTime: "10:00 AM",
    meetingLink: "https://zoom.us/j/123456789",
    status: "completed",
    reminderSent: true,
  },
  {
    id: "APT-002",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    appointmentDate: "2025-01-23",
    appointmentTime: "3:00 PM",
    meetingLink: "https://zoom.us/j/987654321",
    status: "completed",
    reminderSent: true,
  },
  {
    id: "APT-003",
    leadId: "LD-006",
    leadName: "David Kim",
    appointmentDate: "2025-02-03",
    appointmentTime: "11:00 AM",
    meetingLink: "https://zoom.us/j/111222333",
    status: "scheduled",
    reminderSent: false,
  },
  {
    id: "APT-004",
    leadId: "LD-009",
    leadName: "Jessica Park",
    appointmentDate: "2025-01-30",
    appointmentTime: "2:00 PM",
    meetingLink: "https://zoom.us/j/444555666",
    status: "confirmed",
    reminderSent: true,
  },
  {
    id: "APT-005",
    leadId: "LD-011",
    leadName: "Nina Patel",
    appointmentDate: "2025-01-31",
    appointmentTime: "9:00 AM",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    status: "scheduled",
    reminderSent: false,
  },
  {
    id: "APT-006",
    leadId: "LD-003",
    leadName: "Emily Chen",
    appointmentDate: "2025-02-05",
    appointmentTime: "4:00 PM",
    meetingLink: "https://zoom.us/j/777888999",
    status: "scheduled",
    reminderSent: false,
  },
  {
    id: "APT-007",
    leadId: "LD-010",
    leadName: "Chris Anderson",
    appointmentDate: "2025-01-18",
    appointmentTime: "1:00 PM",
    meetingLink: "https://zoom.us/j/000111222",
    status: "no-show",
    reminderSent: true,
  },
];

export const mockFollowUps: FollowUp[] = [
  {
    id: "FU-001",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    followUpNumber: 1,
    followUpMessage: "Hi Sarah, great chatting with you! As discussed, here's a summary of our AI automation packages and pricing details.",
    scheduledTime: "2025-01-23T09:00:00Z",
    status: "sent",
    messageSent: true,
    responseReceived: true,
  },
  {
    id: "FU-002",
    leadId: "LD-001",
    leadName: "Sarah Mitchell",
    followUpNumber: 2,
    followUpMessage: "Sarah, following up on our conversation. Have you had a chance to review the proposal? I'd love to answer any questions.",
    scheduledTime: "2025-01-27T10:00:00Z",
    status: "sent",
    messageSent: true,
    responseReceived: true,
  },
  {
    id: "FU-003",
    leadId: "LD-002",
    leadName: "James Rodriguez",
    followUpNumber: 1,
    followUpMessage: "James, thanks for the demo! Here's a recap of the customer support AI features we discussed.",
    scheduledTime: "2025-01-24T15:00:00Z",
    status: "sent",
    messageSent: true,
    responseReceived: false,
  },
  {
    id: "FU-004",
    leadId: "LD-004",
    leadName: "Michael Foster",
    followUpNumber: 1,
    followUpMessage: "Hi Michael, I noticed you were exploring our healthcare AI solutions. Would you like to schedule a quick call?",
    scheduledTime: "2025-01-29T14:00:00Z",
    status: "pending",
    messageSent: false,
    responseReceived: false,
  },
  {
    id: "FU-005",
    leadId: "LD-005",
    leadName: "Olivia Brown",
    followUpNumber: 1,
    followUpMessage: "Olivia, I wanted to follow up on your interest in our AI design tools. We have new features I think you'd love!",
    scheduledTime: "2025-01-28T11:00:00Z",
    status: "pending",
    messageSent: false,
    responseReceived: false,
  },
  {
    id: "FU-006",
    leadId: "LD-008",
    leadName: "Robert Zhang",
    followUpNumber: 2,
    followUpMessage: "Robert, checking in on the manufacturing AI proposal. Our team is ready to start implementation whenever you're ready.",
    scheduledTime: "2025-01-30T09:00:00Z",
    status: "pending",
    messageSent: false,
    responseReceived: false,
  },
  {
    id: "FU-007",
    leadId: "LD-012",
    leadName: "Tom Wilson",
    followUpNumber: 1,
    followUpMessage: "Tom, great chatting earlier! Here's the logistics AI case study I mentioned. Let me know your thoughts.",
    scheduledTime: "2025-01-27T16:00:00Z",
    status: "sent",
    messageSent: true,
    responseReceived: true,
  },
];

export const mockBusinessKnowledge: BusinessKnowledge = {
  id: "BK-001",
  businessName: "NexusAI Solutions",
  services: [
    "AI Lead Qualification",
    "Automated Appointment Booking",
    "AI Customer Support",
    "Conversational AI Chatbots",
    "AI-Powered CRM",
    "Predictive Analytics",
  ],
  pricing: "Starter: $499/mo | Growth: $999/mo | Enterprise: $2,499/mo | Custom: Contact Us",
  faqs: [
    {
      question: "How does AI lead qualification work?",
      answer: "Our AI analyzes lead behavior, engagement patterns, and conversation context to automatically score and qualify leads based on your ideal customer profile.",
    },
    {
      question: "Can I integrate with my existing CRM?",
      answer: "Yes! We integrate with Salesforce, HubSpot, Pipedrive, and 50+ other platforms via API or native connectors.",
    },
    {
      question: "How long does setup take?",
      answer: "Most businesses are up and running within 48 hours. Enterprise implementations typically take 1-2 weeks.",
    },
    {
      question: "Is there a free trial?",
      answer: "Yes, we offer a 14-day free trial on all plans with full feature access.",
    },
  ],
  hours: "Monday - Friday: 9:00 AM - 6:00 PM EST | Saturday: 10:00 AM - 2:00 PM EST",
  policies: "30-day money-back guarantee. No long-term contracts required. Cancel anytime.",
  bookingLink: "https://calendly.com/nexusai/demo",
};
